Feature: Desktop Version
luftedar/My-Portfolio pull request #5
Opened 2021-09-22 21:40 UTC by luftedar

In this update:

- Update HTML for responsive design.
- Added media queries for responsive design.
- Update Readme File.

2021-09-22 23:09 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @luftedar @praizerema , You did a great job so far 👏🏼 👏🏼 

- The webpage is responsive
- The linter checks are passing
- The Readme file is descriptive

However, here are some points that you need to work on to get your project approved.

## Required changes :

Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-22 23:09 UTC, safafa commented on style.css
> +
![image](https://user-images.githubusercontent.com/43698511/134431999-3f8ea68a-5cda-4d31-89f2-a3dbc84954ab.png)

- [x] As you can see from the picture, for screen width 599px and less the background image for the headline is missing. I think it may be caused by this piece of code. The background image should be visible for the mobile view for screen width 991px and less kindly fix the issue.

2021-09-22 23:09 UTC, safafa commented on style.css
> +    display: none;
![image](https://user-images.githubusercontent.com/43698511/134432768-84fcdc34-9f9b-4a10-b8c2-9953a412ef44.png)

- [ ] As you can see from the picture for desktop view (screen-width 992px and higher) The horizontal scroll bar is showing which means that there's an overflow. Kindly fix the issue.


![image](https://user-images.githubusercontent.com/43698511/134433519-a02457a7-c424-4d60-a865-f51cf385b399.png)

- [ ] In the original design The Title My recent work is followed by 2 rows with 3 projects each. Your webpage looks a bit different for screen-width from 992px to 1199px kindly fix the issue.

2021-09-23 11:01 UTC, luftedar commented
- Fixed Livedemo background display.
- Updated layout between media queries 992px - 1200px.
- Fixed overflow.

2021-09-23 11:40 UTC, dasileker approved these changes
### **Hi @luftedar,** 

### **Project Approved ✅**

![Approved](https://user-images.githubusercontent.com/61562626/134500542-eccf287a-3441-435b-9afb-4b0888c7a689.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-23 11:45 UTC, merged